// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GettingGenreIdValidationtowork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GettingGenreIdValidationtowork));
        
        string IMigrationMetadata.Id
        {
            get { return "201801062005055_Getting GenreId Validation to work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
